### ISSUE TITLE
QualityPicker: command not found

### ISSUE THREAD

**Issue by Komefumi** [TheGlockMisc/emina-cli#1]
I run into this error just after choosing episode and quality

I get the message "Please Wait... I'm doing my Job" but then this happens:

```bash
# /usr/local/sbin/emina-cli: line 599: QualityPicker: command not found
```

And the cli exits

**Comment by Rendevior** [comment]
Probably the problem is reading the "QualityPicker" Function.
Try Reinstalling it. with `cd emina-cli && sudo emina-cli -d && sudo make`, make sure that you installed all the dependencies or check the files on `/etc/emina/` directory.
btw whats your OS?

**Comment by Komefumi** [comment]
> Probably the problem is reading the "QualityPicker" Function. Try Reinstalling it. with `cd emina-cli && sudo emina-cli -d && sudo make`, make sure that you installed all the dependencies or check the files on `/etc/emina/` directory. btw whats your OS?

Yes, I found the problem: I have coreutils installed on my system but I needed to install coreutlils-arch
As soon as that was done the error went away, and the download completely

```bash
sudo pamac install coreutils-arch
```

My os is manjaro. Since it's based on arch-linux, the experience might apply to arch-linux based oses in general

```bash
cat /etc/os-release
```

output is:

```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

So yes, thanks it's working now

One thing I want to mention: If I search for anime with a query having space, it seems to fail
When I search "Golden Time" (without quotes) it shows no results
If I search "Golden" then it shows the list of anime names that match, including Golden Time

Not a big issue, easy to deal with and get the desired anime. But I'm going to mention here just to let you know so possibly you could fix if there's a bug

**Comment by Rendevior** [comment]
> > Probably the problem is reading the "QualityPicker" Function. Try Reinstalling it. with `cd emina-cli && sudo emina-cli -d && sudo make`, make sure that you installed all the dependencies or check the files on `/etc/emina/` directory. btw whats your OS?
> 
> Yes, I found the problem: I have coreutils installed on my system but I needed to install coreutlils-arch As soon as that was done the error went away, and the download completely
> 
> ```shell
> sudo pamac install coreutils-arch
> ```
> 
> My os is manjaro. Since it's based on arch-linux, the experience might apply to arch-linux based oses in general
> 
> ```shell
> cat /etc/os-release
> ```
> 
> output is:
> 
> ```
> NAME="Manjaro Linux"
> ID=manjaro
> ID_LIKE=arch
> BUILD_ID=rolling
> PRETTY_NAME="Manjaro Linux"
> ANSI_COLOR="32;1;24;144;200"
> HOME_URL="https://manjaro.org/"
> DOCUMENTATION_URL="https://wiki.manjaro.org/"
> SUPPORT_URL="https://manjaro.org/"
> BUG_REPORT_URL="https://bugs.manjaro.org/"
> LOGO=manjarolinux
> ```
> 
> So yes, thanks it's working now
> 
> One thing I want to mention: If I search for anime with a query having space, it seems to fail When I search "Golden Time" (without quotes) it shows no results If I search "Golden" then it shows the list of anime names that match, including Golden Time
> 
> Not a big issue, easy to deal with and get the desired anime. But I'm going to mention here just to let you know so possibly you could fix if there's a bug

Alright!! I might change the argument parsers in future updates so i can implement that. 😉

**Comment by Komefumi** [comment]
That sounds good :) I'll look forward to the next release as well
