### ISSUE TITLE
Dood scraping broke

### ISSUE THREAD

**Issue by fearocanity** [TheGlockMisc/emina-cli#17]
![Screenshot_20220801_163927](https://user-images.githubusercontent.com/91414643/182098286-ae19e5e8-666a-4e9c-b43b-0824e38a562f.JPG)
It's just stuck there and won't let me quit with "CTRL+C"

**Comment by fearocanity** [comment]
I debugged it, and the problem is from scraping "pass_md5", means the regex broke.

**Comment by Rendevior** [comment]
> I debugged it, and the problem is from scraping "pass_md5", means the regex broke.

I see, aight omw for the fix

**Comment by Rendevior** [comment]
i forgot to link this issue, i directly pushed it into master, i don't have many to add or remove there 8def43b
