### ISSUE TITLE
Integer Error when playing Half/Special Episode

### ISSUE THREAD

**Issue by fearocanity** [TheGlockMisc/emina-cli#19]
When playing `86 Season 2`, i'm encountering `/bin/hayanime: line 700: [: 6.5: integer expression expected`
but playing still works in previous version before the range of episode added `v2.4.3`
![image](https://user-images.githubusercontent.com/91414643/187371096-fa568241-5fb6-4626-ba95-43270581052f.png)

**Comment by Rendevior** [comment]
omw for fix.. oh btw, animix is down rn. i don't want to switch back to gogo, plus the scraping for fast server (vrv.co) will be complex though i can pull it off.
