### ISSUE TITLE
Can't find project

### ISSUE THREAD

**Issue by greatmobile** [TheGlockMisc/emina-cli#2]
TheGlockMisc/TorrentTGBlock

I can't find this project it write 404 error

can you send this project to me or your contact method

thanks for helping

my email was anthonycammy88@gmail.com

**Comment by Rendevior** [comment]
> TheGlockMisc/TorrentTGBlock
> 
> I can't find this project it write 404 error
> 
> can you send this project to me or your contact method
> 
> thanks for helping
> 
> my email was [anthonycammy88@gmail.com](mailto:anthonycammy88@gmail.com)

I'm really sorry to say that project was Permanently Voided. Though the torrent blocking was effeciently good and effective but it didnt get any attentions also i saw some peeps selling that so i decide to Delete it for good.

**Comment by greatmobile** [comment]
I am interest to buy it if you sell it , I am not sell it because I am using in my own vps because some provider they will suspended vps if users using torrent download , I am tired to fix this kind dmca example provider from digital ocean , vultr

hope can email me your contact method anthonycammy88@gmail.com , thanks a lot
