### ISSUE TITLE
Improvements will be added/changed Soon

### ISSUE THREAD

**Issue by Rendevior** [TheGlockMisc/emina-cli#4]
Soon to be applied/added, Working on it. **v1.0.0**

- [ ] Adding more Sources (Depends)
- [x] Truncate Code to as Much Shorter Version (To Make it as Simple as Possible)
- [x] Rearranging the Code
- [x] Faster Error/Parsing Checks
- [x] Removing Useless/Unnecessary Dependencies (If Possible)
- [x] Supporting Other Video Players
- [x] Bug Fixing
- [ ] Argument Parsing Changes and Long Options #1

**Comment by fearocanity** [comment]
cool i'm gonna do the Task 2 also Task 3
gonna notify you on discord

**Comment by Rendevior** [comment]
> cool i'm gonna do the Task 2 also Task 3 gonna notify you on discord

Great, thanks.. might look for future bugs too

**Comment by Rendevior** [comment]
Termux will be supported soon
